cores: 4
jobs: 4
configfile: workflow/config/synthetic.yaml
latency-wait: 30
rerun-incomplete: true
keep-going: false
printshellcmds: true
show-failed-logs: true
default-resources:
  mem_mb: 2048
resources:
  mem_mb: 12288
