cores: 2
jobs: 2
configfile: workflow/config/ci.yaml
latency-wait: 15
rerun-incomplete: true
keep-going: false
printshellcmds: true
show-failed-logs: true
default-resources:
  mem_mb: 1024
resources:
  mem_mb: 4096
